//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z23 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCore() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("z23.ResourceCore", typeof(ResourceCore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] arrow_up_left_circle {
            get {
                object obj = ResourceManager.GetObject("arrow_up_left_circle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:b [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string bootstrap {
            get {
                return ResourceManager.GetString("bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under the MIT license
        /// */
        ///if(&quot;undefined&quot;==typeof jQuery)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery&quot;);+function(a){&quot;use strict&quot;;var b=a.fn.jquery.split(&quot; &quot;)[0].split(&quot;.&quot;);if(b[0]&lt;2&amp;&amp;b[1]&lt;9||1==b[0]&amp;&amp;9==b[1]&amp;&amp;b[2]&lt;1||b[0]&gt;3)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery version 1.9.1 or higher, but lower than version 4&quot;)}(jQuery),+function(a){&quot;use strict&quot;;function b(){var a=document.createE [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string bootstrap1 {
            get {
                return ResourceManager.GetString("bootstrap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка формирования разметки:Возможно нарушена партикулярность тегов..
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Генерация шаблона документа
        ///Запускаем программу в нужной директории с правами на запись
        ///В директории создается папка static с подключаемыми ресурсами
        ///Создается папка content для содержания картинок документа.
        ///Создается файл шаблона tenplateindex.txt ( шаблон документа)
        ///Создается index.html этого шаблона.
        ///Запускается на браузере по умолчанию.
        ///.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;My Help&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;static/bootstrap.css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;static/main.css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;static/main2.css&quot;&gt;
        ///    &lt;link href=&quot;static/prism.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;script src=&quot;static/prism.js&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/components/prism-json.min.js&quot;&gt;&lt;/scrip [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string innerindex {
            get {
                return ResourceManager.GetString("innerindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string isHowHelpJson {
            get {
                return ResourceManager.GetString("isHowHelpJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /*! jQuery v1.12.0 | (c) jQuery Foundation | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=a.document,e=c.slice,f=c.concat,g=c.push,h=c.indexOf,i={},j=i.toString,k=i.hasOwnProperty,l={},m=&quot;1.12.0&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[\s\uFEFF\xA0]+| [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string jquery_1 {
            get {
                return ResourceManager.GetString("jquery_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /*
        ///    DEMO STYLE
        ///*/
        ///@import &quot;https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&quot;;
        ///
        ///
        ///body {
        ///    font-family: &apos;Poppins&apos;, sans-serif;
        ///    background: #fafafa;
        ///}
        ///
        ///p {
        ///    font-family: &apos;Poppins&apos;, sans-serif;
        ///    font-size: 1.3em;
        ///    font-weight: 300;
        ///    line-height: 1.7em;
        ///    color: rgba(28, 9, 4, 0.95);
        ///}
        ///
        ///a, a:hover, a:focus {
        ///    color: inherit;
        ///    text-decoration: none;
        ///    transition: all 0.3s;
        ///}
        ///
        ///.navbar {
        ///    padding: 15px 10px;
        ///    background: #fff;
        ///    border: none;
        ///    border-radi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /* The sidebar menu */
        ///.sidenav {
        ///    height: 100%; /* Full-height: remove this if you want &quot;auto&quot; height */
        ///    width: 300px; /* Set the width of the sidebar */
        ///    position: fixed; /* Fixed Sidebar (stay in place on scroll) */
        ///    z-index: 1; /* Stay on top */
        ///    top: 0; /* Stay at the top */
        ///    left: 0;
        ///    background-color: #111; /* Black */
        ///    overflow-x: hidden; /* Disable horizontal scroll */
        ///    padding-top: 20px;
        ///}
        ///
        ////* The navigation menu links */
        ///.sidenav a {
        ///    padding: 6px 8px 6px 16px;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string main2 {
            get {
                return ResourceManager.GetString("main2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string pre {
            get {
                return ResourceManager.GetString("pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /* PrismJS 1.23.0
        ///https://prismjs.com/download.html#themes=prism&amp;languages=markup+css+clike+javascript+abap+abnf+actionscript+ada+agda+al+antlr4+apacheconf+apex+apl+applescript+aql+arduino+arff+asciidoc+aspnet+asm6502+autohotkey+autoit+bash+basic+batch+bbcode+birb+bison+bnf+brainfuck+brightscript+bro+bsl+c+csharp+cpp+cfscript+chaiscript+cil+clojure+cmake+cobol+coffeescript+concurnas+csp+coq+crystal+css-extras+csv+cypher+d+dart+dataweave+dax+dhall+diff+django+dns-zone-file+docker+dot+ebnf+editorconfig+eiffel [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string prism {
            get {
                return ResourceManager.GetString("prism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /* PrismJS 1.23.0
        ///https://prismjs.com/download.html#themes=prism&amp;languages=markup+css+clike+javascript+abap+abnf+actionscript+ada+agda+al+antlr4+apacheconf+apex+apl+applescript+aql+arduino+arff+asciidoc+aspnet+asm6502+autohotkey+autoit+bash+basic+batch+bbcode+birb+bison+bnf+brainfuck+brightscript+bro+bsl+c+csharp+cpp+cfscript+chaiscript+cil+clojure+cmake+cobol+coffeescript+concurnas+csp+coq+crystal+css-extras+csv+cypher+d+dart+dataweave+dax+dhall+diff+django+dns-zone-file+docker+dot+ebnf+editorconfig+eiffel [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string prism1 {
            get {
                return ResourceManager.GetString("prism1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ***************precompiler*******************.
        /// </summary>
        internal static string Program_Main________________precompiler___________________ {
            get {
                return ResourceManager.GetString("Program_Main________________precompiler___________________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;menu text=&quot;Я помню чудное мгновенье&quot; textmenu=&quot;Я помню &quot;/&gt;
        /// Я помню чудное мгновенье
        ///
        ///Передо мной явилась ты,
        ///Как мимолетное виденье,
        ///Как гений чистой красоты.
        ///&lt;menu text=&quot;В томленьях&quot; /&gt;
        /// В томленьях грусти безнадежной
        ///В тревогах шумной суеты,
        ///Звучал мне долго голос нежный
        ///И снились милые черты.
        ///Шли годы. Бурь порыв мятежный
        ///Рассеял прежние мечты,
        ///И я забыл твой голос нежный,
        ///Твои небесные черты.
        ///&lt;menu text=&quot;Тянулись тихо&quot; /&gt;
        ///В глуши, во мраке заточенья
        ///Тянулись тихо дни мои
        ///Без божества [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string templateindex {
            get {
                return ResourceManager.GetString("templateindex", resourceCulture);
            }
        }
    }
}
